# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build WebAssembly then Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Ebitengine dependencies
      run: sudo apt install libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      run: go build -v ./...
      
    - name: Build Web Assembly artifact
      run: GOOS=js GOARCH=wasm go build -o ebitengine-boids.wasm github.com/rangzen/go-ebiten-boids

    - name: Upload Web Assembly artifact
      uses: actions/upload-artifact@v3
      with:
        name: wasm
        path: ebitengine-boids.wasm

    - name: Test
      run: go test -v ./...

  deploy:
    name: Deploy to GitHub pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Download Web Assembly artifact
        uses: actions/download-artifact@v3
        with:
          name: wasm
          path: www/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: www/
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
